version: 2
jobs:
  build:
    working_directory: ~/wd
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install -r requirements.txt
            sudo pip3 install pytest pytest-cov
      - run:
          command: | 
            py.test --cov=gitremind

